"""Memory-first LLM analysis toolkit."""

from .attention_debugger import AttentionStats, analyze_qk_attention, attention_stats_to_text, collect_attention_stats
from .benchmark import BenchmarkConfig, BenchmarkResult, benchmark_callable, benchmark_decode, benchmark_forward, compare_benchmarks
from .bytes import dtype_size_bytes, format_bytes, parse_bytes
from .compare_report import CompareReport, compare_report_to_html, scoreboard_to_html, write_compare_html, write_scoreboard_html
from .estimates import MemoryEstimate, TransformerConfig, estimate_transformer_memory, preset_config
from .html_report import trace_timeline_to_html, trace_to_html, write_timeline_html, write_trace_html
from .inspector import ModelArchitectureInfo, inspect_model, load_hf_model
from .ir import GraphSpec, OperationSpec, TensorSpec
from .kernels import (
    KernelConfig,
    apply_rope,
    chunked_cross_entropy,
    kernel,
    linear_cross_entropy,
    qkv_rope_attention,
    qkv_rope_attention_cached,
    quantized_kv_attention,
    rms_norm,
    rms_norm_manual_backward,
    scaled_dot_product_attention,
    swiglu,
    triton_apply_rope,
    triton_dequantize_int8_per_token,
    triton_quantize_int8_per_token,
    triton_rms_norm,
    triton_swiglu_activation,
)
from .kv_cache import (
    DecodeConfig,
    DecodeResult,
    KVCacheConfig,
    PagedKVCache,
    QuantizedStaticKVCache,
    StaticKVCache,
    dequantize_int8_per_token,
    dequantize_uint8_per_token,
    greedy_decode,
    quantize_int8_per_token,
    quantize_uint8_per_token,
    resolve_kv_storage_dtype,
    sample_next_token,
)
from .kv_quality import AttentionKVQualityResult, KVQualityResult, evaluate_attention_kv_quality, evaluate_int8_kv_quality, evaluate_kv_quantization_quality
from .memory_policy import MemoryPolicy, choose_memory_policy
from .optimization_report import OptimizationFinding, OptimizationReport, infer_findings
from .patchers import PackedQKVAttentionAdapter, PatchReport, optimize_hf_model, optimize_llama_qwen_attention
from .planner import BufferPlan, MemoryPlanner, TensorLifetime
from .torch_debugger import TorchTrace, trace_forward
from .triton_kernels import triton_available

__all__ = [
    "AttentionKVQualityResult",
    "AttentionStats",
    "BenchmarkConfig",
    "BenchmarkResult",
    "BufferPlan",
    "CompareReport",
    "DecodeConfig",
    "DecodeResult",
    "GraphSpec",
    "KVCacheConfig",
    "KVQualityResult",
    "KernelConfig",
    "MemoryEstimate",
    "MemoryPlanner",
    "MemoryPolicy",
    "ModelArchitectureInfo",
    "OperationSpec",
    "OptimizationFinding",
    "OptimizationReport",
    "PackedQKVAttentionAdapter",
    "PagedKVCache",
    "PatchReport",
    "QuantizedStaticKVCache",
    "StaticKVCache",
    "TensorLifetime",
    "TensorSpec",
    "TorchTrace",
    "TransformerConfig",
    "analyze_qk_attention",
    "apply_rope",
    "attention_stats_to_text",
    "benchmark_callable",
    "benchmark_decode",
    "benchmark_forward",
    "choose_memory_policy",
    "chunked_cross_entropy",
    "collect_attention_stats",
    "compare_benchmarks",
    "compare_report_to_html",
    "dequantize_int8_per_token",
    "dequantize_uint8_per_token",
    "dtype_size_bytes",
    "estimate_transformer_memory",
    "evaluate_attention_kv_quality",
    "evaluate_int8_kv_quality",
    "evaluate_kv_quantization_quality",
    "format_bytes",
    "greedy_decode",
    "infer_findings",
    "inspect_model",
    "kernel",
    "linear_cross_entropy",
    "load_hf_model",
    "optimize_hf_model",
    "optimize_llama_qwen_attention",
    "parse_bytes",
    "preset_config",
    "qkv_rope_attention",
    "qkv_rope_attention_cached",
    "quantize_int8_per_token",
    "quantize_uint8_per_token",
    "quantized_kv_attention",
    "resolve_kv_storage_dtype",
    "rms_norm",
    "rms_norm_manual_backward",
    "sample_next_token",
    "scoreboard_to_html",
    "trace_timeline_to_html",
    "write_scoreboard_html",
    "write_timeline_html",
    "scaled_dot_product_attention",
    "swiglu",
    "trace_forward",
    "trace_to_html",
    "triton_apply_rope",
    "triton_available",
    "triton_dequantize_int8_per_token",
    "triton_quantize_int8_per_token",
    "triton_rms_norm",
    "triton_swiglu_activation",
    "write_compare_html",
    "write_trace_html",
]

