from __future__ import annotations

from .benchmark_store import (
    BENCHMARK_SCHEMA_VERSION,
    BenchmarkComparison,
    BenchmarkGateConfig,
    BenchmarkGateResult,
    BenchmarkHistory,
    BenchmarkMetadata,
    BenchmarkRecord,
    assert_no_regressions,
    benchmark_history,
    benchmark_history_gate,
    benchmark_gate,
    collect_run_metadata,
    compare_benchmark_records,
    compare_record_sets,
    read_benchmark_csv,
    read_benchmark_json,
    record_from_benchmark,
    records_from_suite,
    read_benchmark_files,
    write_benchmark_csv,
    write_benchmark_json,
)
from .backend_registry import BackendInfo, BackendPlugin, BackendRegistry, load_backend_entrypoints
from .backends.cutile import CuTileRuntimeInfo, detect_cutile_runtime
from .env_certification import ENV_CERTIFICATION_SCHEMA_VERSION, EnvironmentCertificationReport, certify_environment
from .hardware import HARDWARE_PROFILE_SCHEMA_VERSION, HardwareProfile, detect_hardware_profile
from .hf_adapter import (
    BaseFamilyMemoryAdapter,
    DeepSeekMemoryAdapter,
    FamilyAdapterCapabilities,
    FalconMemoryAdapter,
    GemmaMemoryAdapter,
    GPTNeoXMemoryAdapter,
    HFAdapterInfo,
    LlamaMemoryAdapter,
    MemoryFirstGenerateResult,
    MemoryFirstHFAdapter,
    MemoryFirstHFConfig,
    MemoryFirstTransformersCache,
    MistralMemoryAdapter,
    MixtralMemoryAdapter,
    PhiMemoryAdapter,
    Qwen3MemoryAdapter,
    QwenMemoryAdapter,
    adapter_satisfies_contract,
    detect_hf_adapter_info,
    install_memory_first_generate,
    list_memory_adapters,
    make_transformers_cache_from_model,
    memory_first_generate,
    memory_first_generate_hf,
    register_memory_adapter,
    select_memory_adapter,
    supports_transformers_cache_api,
)
from .hf_adapter_contract import MemoryAdapterProtocol
from .hf_adapter_matrix import (
    HF_ADAPTER_MATRIX_SCHEMA_VERSION,
    HFAdapterMatrixEntry,
    hf_adapter_matrix_to_text,
    production_hf_adapter_matrix,
)
from .hf_cache_certification import (
    HF_CACHE_CERTIFICATION_SCHEMA_VERSION,
    HFCacheCertificationCase,
    HFCacheCertificationReport,
    HFCacheCertificationResult,
    assert_hf_cache_certified,
    certify_hf_cache,
    certify_hf_cache_model,
    hf_cache_certification_to_html,
)
from .hf_cache_policy import HFCachePolicy, HFCachePolicyDecision, select_hf_cache_policy
from .hf_cache_profiles import (
    CacheProfileRegistry,
    DEFAULT_QUANTIZED_CACHE_PROFILES,
    HF_CACHE_PROFILE_SCHEMA_VERSION,
    QuantizedCacheCertificationProfile,
    load_quantized_cache_profiles,
    promote_profile,
    select_quantized_cache_profile,
    write_quantized_cache_profiles,
)
from .hf_runtime import HFGenerateRun, HFMemoryFirstBenchmark, assert_hf_benchmark_passed, benchmark_memory_first_hf_generate
from .kernel_policy import KernelPolicy, KernelSelection, default_kernel_policy, select_kernel_policy
from .memory_profiler import (
    MEMORY_PROFILE_SCHEMA_VERSION,
    CUDAMemorySample,
    DecodeMemoryProfile,
    MemoryAttribution,
    MemoryProfileComparison,
    compare_memory_profiles,
    profile_decode_memory,
    write_memory_profile_html,
    write_memory_profile_json,
)
from .quality_suite import (
    QUALITY_SCHEMA_VERSION,
    QualityRegressionResult,
    QualityThresholds,
    assert_quality_regression,
    run_quality_regression,
)

PRODUCTION_API_VERSION = "0.1"
STABILITY_POLICY = (
    "llm_memlab.production exports stable APIs for the current 0.x line. "
    "Experimental kernels and adapters stay in llm_memlab.experimental until certification promotes them."
)

__all__ = [
    "BENCHMARK_SCHEMA_VERSION",
    "BackendInfo",
    "BackendPlugin",
    "BackendRegistry",
    "BenchmarkComparison",
    "BenchmarkGateConfig",
    "BenchmarkGateResult",
    "BenchmarkHistory",
    "BenchmarkMetadata",
    "BenchmarkRecord",
    "BaseFamilyMemoryAdapter",
    "CUDAMemorySample",
    "CacheProfileRegistry",
    "CuTileRuntimeInfo",
    "DeepSeekMemoryAdapter",
    "ENV_CERTIFICATION_SCHEMA_VERSION",
    "EnvironmentCertificationReport",
    "FalconMemoryAdapter",
    "GemmaMemoryAdapter",
    "GPTNeoXMemoryAdapter",
    "HARDWARE_PROFILE_SCHEMA_VERSION",
    "DEFAULT_QUANTIZED_CACHE_PROFILES",
    "DecodeMemoryProfile",
    "FamilyAdapterCapabilities",
    "HFAdapterInfo",
    "HFAdapterMatrixEntry",
    "HF_ADAPTER_MATRIX_SCHEMA_VERSION",
    "HF_CACHE_CERTIFICATION_SCHEMA_VERSION",
    "HF_CACHE_PROFILE_SCHEMA_VERSION",
    "HFCacheCertificationCase",
    "HFCacheCertificationReport",
    "HFCacheCertificationResult",
    "HFCachePolicy",
    "HFCachePolicyDecision",
    "HFGenerateRun",
    "HFMemoryFirstBenchmark",
    "HardwareProfile",
    "KernelPolicy",
    "KernelSelection",
    "LlamaMemoryAdapter",
    "MEMORY_PROFILE_SCHEMA_VERSION",
    "MemoryFirstGenerateResult",
    "MemoryFirstHFAdapter",
    "MemoryFirstHFConfig",
    "MemoryFirstTransformersCache",
    "MemoryAdapterProtocol",
    "MemoryProfileComparison",
    "MemoryAttribution",
    "MistralMemoryAdapter",
    "MixtralMemoryAdapter",
    "PhiMemoryAdapter",
    "QUALITY_SCHEMA_VERSION",
    "QualityRegressionResult",
    "QualityThresholds",
    "QwenMemoryAdapter",
    "Qwen3MemoryAdapter",
    "STABILITY_POLICY",
    "assert_no_regressions",
    "adapter_satisfies_contract",
    "assert_quality_regression",
    "assert_hf_benchmark_passed",
    "assert_hf_cache_certified",
    "benchmark_gate",
    "benchmark_history",
    "benchmark_history_gate",
    "benchmark_memory_first_hf_generate",
    "certify_hf_cache",
    "certify_hf_cache_model",
    "certify_environment",
    "collect_run_metadata",
    "compare_benchmark_records",
    "compare_memory_profiles",
    "compare_record_sets",
    "default_kernel_policy",
    "detect_hf_adapter_info",
    "detect_cutile_runtime",
    "detect_hardware_profile",
    "install_memory_first_generate",
    "list_memory_adapters",
    "load_backend_entrypoints",
    "load_quantized_cache_profiles",
    "make_transformers_cache_from_model",
    "memory_first_generate",
    "memory_first_generate_hf",
    "profile_decode_memory",
    "production_hf_adapter_matrix",
    "promote_profile",
    "read_benchmark_csv",
    "read_benchmark_files",
    "read_benchmark_json",
    "record_from_benchmark",
    "register_memory_adapter",
    "records_from_suite",
    "run_quality_regression",
    "select_kernel_policy",
    "select_hf_cache_policy",
    "select_memory_adapter",
    "select_quantized_cache_profile",
    "supports_transformers_cache_api",
    "write_benchmark_csv",
    "write_benchmark_json",
    "write_quantized_cache_profiles",
    "write_memory_profile_html",
    "write_memory_profile_json",
    "hf_cache_certification_to_html",
    "hf_adapter_matrix_to_text",
]
